title: "Ultima Online: New Renaissance"
description: "The complete guide to Ultima Online: New Renaissance - Player guides, quests, skills, and community resources"
baseurl: "/uo-renaissance-wiki"
url: "https://newrenaissanceuo.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and meta
author: "Ultima Online: New Renaissance Community"

# Navigation structure
header_pages:
  - getting-started.md
  - game-guides.md
  - quests.md
  - skills.md
  - pvp-guide.md
  - housing.md
  - events.md
  - server-info.md
  - community.md

# Custom variables for the wiki
game_name: "Ultima Online: New Renaissance"
discord_invite: "https://discord.gg/aynT7Cv82d"

# Wiki-specific settings
show_excerpts: true
date_format: "%B %d, %Y"

# Custom styling
minima:
  skin: dark

# Collections for organized content
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  quests:
    output: true
    permalink: /:collection/:name/
  skills:
    output: true
    permalink: /:collection/:name/

# Default layouts for collections
defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "quests"
    values:
      layout: "quest"
  - scope:
      path: ""
      type: "skills"
    values:
      layout: "skill"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/